version: '3'

vars:
  APP_NAME: regression-api

env:
  FLASK_APP: app.py

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Run Flask application in development mode
    cmds:
      - cp -n .env.example .env || true
      - docker compose up --build
    env:
      FLASK_ENV: development
      FLASK_CMD: python app.py

  prod:
    desc: Run Flask application in production mode using Gunicorn
    cmds:
      - cp -n .env.production .env || true
      - docker compose up --build
    env:
      FLASK_ENV: production
      FLASK_CMD: gunicorn --bind 0.0.0.0:8000 app:app --workers=4

  build:
    desc: Build Docker image
    cmds:
      - docker compose build

  clean:
    desc: Remove Docker containers, images, and volumes
    cmds:
      - docker compose down -v --rmi local

  lint:
    desc: Run linting on Python files
    cmds:
      - docker compose run --rm web flake8 .

  test:
    desc: Run tests
    cmds:
      - docker compose run --rm web pytest